# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JansenWidget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Jansen(object):
    def setupUi(self, Jansen):
        Jansen.setObjectName("Jansen")
        Jansen.resize(1050, 727)
        self.centralwidget = QtWidgets.QWidget(Jansen)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setLineWidth(1)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(6)
        self.splitter.setObjectName("splitter")
        self.screen = QJansenScreen(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.screen.sizePolicy().hasHeightForWidth())
        self.screen.setSizePolicy(sizePolicy)
        self.screen.setMinimumSize(QtCore.QSize(640, 480))
        self.screen.setObjectName("screen")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setObjectName("tabWidget")
        self.tabVideo = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabVideo.sizePolicy().hasHeightForWidth())
        self.tabVideo.setSizePolicy(sizePolicy)
        self.tabVideo.setMinimumSize(QtCore.QSize(0, 0))
        self.tabVideo.setAccessibleName("")
        self.tabVideo.setAccessibleDescription("")
        self.tabVideo.setObjectName("tabVideo")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabVideo)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupSource = QtWidgets.QGroupBox(self.tabVideo)
        self.groupSource.setObjectName("groupSource")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupSource)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bcamera = QtWidgets.QRadioButton(self.groupSource)
        self.bcamera.setChecked(True)
        self.bcamera.setObjectName("bcamera")
        self.horizontalLayout_3.addWidget(self.bcamera)
        self.bfilters = QtWidgets.QRadioButton(self.groupSource)
        self.bfilters.setObjectName("bfilters")
        self.horizontalLayout_3.addWidget(self.bfilters)
        spacerItem = QtWidgets.QSpacerItem(283, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.fps = QtWidgets.QDoubleSpinBox(self.groupSource)
        self.fps.setReadOnly(True)
        self.fps.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.fps.setDecimals(1)
        self.fps.setMaximum(1000.0)
        self.fps.setProperty("value", 10.0)
        self.fps.setObjectName("fps")
        self.horizontalLayout_3.addWidget(self.fps)
        self.verticalLayout_4.addWidget(self.groupSource)
        self.groupDvr = QtWidgets.QGroupBox(self.tabVideo)
        self.groupDvr.setMinimumSize(QtCore.QSize(0, 0))
        self.groupDvr.setObjectName("groupDvr")
        self.dvrLayout_2 = QtWidgets.QVBoxLayout(self.groupDvr)
        self.dvrLayout_2.setContentsMargins(2, 2, 2, 2)
        self.dvrLayout_2.setSpacing(1)
        self.dvrLayout_2.setObjectName("dvrLayout_2")
        self.dvr = QDVR(self.groupDvr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dvr.sizePolicy().hasHeightForWidth())
        self.dvr.setSizePolicy(sizePolicy)
        self.dvr.setMinimumSize(QtCore.QSize(0, 0))
        self.dvr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dvr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dvr.setObjectName("dvr")
        self.dvrLayout_2.addWidget(self.dvr)
        self.verticalLayout_4.addWidget(self.groupDvr)
        self.groupCamera = QtWidgets.QGroupBox(self.tabVideo)
        self.groupCamera.setMinimumSize(QtCore.QSize(0, 0))
        self.groupCamera.setObjectName("groupCamera")
        self.cameraLayout = QtWidgets.QVBoxLayout(self.groupCamera)
        self.cameraLayout.setContentsMargins(2, 2, 2, 2)
        self.cameraLayout.setSpacing(1)
        self.cameraLayout.setObjectName("cameraLayout")
        self.camera = QtWidgets.QFrame(self.groupCamera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera.sizePolicy().hasHeightForWidth())
        self.camera.setSizePolicy(sizePolicy)
        self.camera.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.camera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.camera.setObjectName("camera")
        self.cameraLayout.addWidget(self.camera)
        self.verticalLayout_4.addWidget(self.groupCamera)
        self.groupFilters = QtWidgets.QGroupBox(self.tabVideo)
        self.groupFilters.setMinimumSize(QtCore.QSize(0, 0))
        self.groupFilters.setObjectName("groupFilters")
        self.filterLayout_2 = QtWidgets.QVBoxLayout(self.groupFilters)
        self.filterLayout_2.setContentsMargins(2, 2, 2, 2)
        self.filterLayout_2.setSpacing(1)
        self.filterLayout_2.setObjectName("filterLayout_2")
        self.filters = QVideoFilter(self.groupFilters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filters.sizePolicy().hasHeightForWidth())
        self.filters.setSizePolicy(sizePolicy)
        self.filters.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filters.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filters.setObjectName("filters")
        self.filterLayout_2.addWidget(self.filters)
        self.verticalLayout_4.addWidget(self.groupFilters)
        spacerItem1 = QtWidgets.QSpacerItem(20, 338, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.tabWidget.addTab(self.tabVideo, "")
        self.tabHistogram = QtWidgets.QWidget()
        self.tabHistogram.setObjectName("tabHistogram")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabHistogram)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.histogram = QHistogram(self.tabHistogram)
        self.histogram.setObjectName("histogram")
        self.verticalLayout_2.addWidget(self.histogram)
        self.tabWidget.addTab(self.tabHistogram, "")
        self.tabVision = QtWidgets.QWidget()
        self.tabVision.setObjectName("tabVision")
        self.visionLayout = QtWidgets.QVBoxLayout(self.tabVision)
        self.visionLayout.setObjectName("visionLayout")
        self.vision = QtWidgets.QWidget(self.tabVision)
        self.vision.setObjectName("vision")
        self.visionLayout.addWidget(self.vision)
        self.tabWidget.addTab(self.tabVision, "")
        self.tabHelp = QtWidgets.QWidget()
        self.tabHelp.setObjectName("tabHelp")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabHelp)
        self.verticalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_6.setSpacing(4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.bback = QtWidgets.QPushButton(self.tabHelp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bback.sizePolicy().hasHeightForWidth())
        self.bback.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/go-previous.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bback.setIcon(icon)
        self.bback.setObjectName("bback")
        self.verticalLayout_6.addWidget(self.bback)
        self.browser = QtWebEngineWidgets.QWebEngineView(self.tabHelp)
        self.browser.setProperty("url", QtCore.QUrl("qrc:/help/help/jansen.html"))
        self.browser.setObjectName("browser")
        self.verticalLayout_6.addWidget(self.browser)
        self.tabWidget.addTab(self.tabHelp, "")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        Jansen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Jansen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        Jansen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Jansen)
        self.statusbar.setObjectName("statusbar")
        Jansen.setStatusBar(self.statusbar)
        self.actionSavePhoto = QtWidgets.QAction(Jansen)
        self.actionSavePhoto.setObjectName("actionSavePhoto")
        self.actionSavePhotoAs = QtWidgets.QAction(Jansen)
        self.actionSavePhotoAs.setObjectName("actionSavePhotoAs")
        self.actionQuit = QtWidgets.QAction(Jansen)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionSavePhoto)
        self.menuFile.addAction(self.actionSavePhotoAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Jansen)
        self.tabWidget.setCurrentIndex(2)
        self.actionQuit.triggered.connect(Jansen.close)
        self.screen.sigFPS['double'].connect(self.fps.setValue)
        self.dvr.recording['bool'].connect(self.camera.setDisabled)
        self.dvr.recording['bool'].connect(self.filters.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Jansen)

    def retranslateUi(self, Jansen):
        _translate = QtCore.QCoreApplication.translate
        Jansen.setWindowTitle(_translate("Jansen", "Jansen"))
        self.tabWidget.setStatusTip(_translate("Jansen", "Record from video camera directly"))
        self.groupSource.setTitle(_translate("Jansen", "Recording Source"))
        self.bcamera.setStatusTip(_translate("Jansen", "Record raw video from camera"))
        self.bcamera.setText(_translate("Jansen", "Camera"))
        self.bfilters.setStatusTip(_translate("Jansen", "Record filtered video stream"))
        self.bfilters.setText(_translate("Jansen", "Filters"))
        self.fps.setSuffix(_translate("Jansen", " fps"))
        self.groupDvr.setTitle(_translate("Jansen", "Video Recorder"))
        self.groupCamera.setTitle(_translate("Jansen", "Video Camera"))
        self.groupFilters.setTitle(_translate("Jansen", "Video Filters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVideo), _translate("Jansen", "Video"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHistogram), _translate("Jansen", "Histogram"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVision), _translate("Jansen", "Vision"))
        self.bback.setText(_translate("Jansen", "Back"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHelp), _translate("Jansen", "Help"))
        self.menuFile.setTitle(_translate("Jansen", "File"))
        self.actionSavePhoto.setText(_translate("Jansen", "Save Photo"))
        self.actionSavePhoto.setShortcut(_translate("Jansen", "Ctrl+S"))
        self.actionSavePhotoAs.setText(_translate("Jansen", "Save Photo As ..."))
        self.actionSavePhotoAs.setShortcut(_translate("Jansen", "Ctrl+A"))
        self.actionQuit.setText(_translate("Jansen", "Quit"))
        self.actionQuit.setShortcut(_translate("Jansen", "Ctrl+Q"))

from PyQt5 import QtWebEngineWidgets
from jansenlib.QDVR.QDVR import QDVR
from jansenlib.QHistogram.QHistogram import QHistogram
from jansenlib.QJansenScreen import QJansenScreen
from jansenlib.video.QVideoFilter.QVideoFilter import QVideoFilter
import help_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Jansen = QtWidgets.QMainWindow()
    ui = Ui_Jansen()
    ui.setupUi(Jansen)
    Jansen.show()
    sys.exit(app.exec_())

