# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasks/lib/doVisionWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_doVisionWidget(object):
    def setupUi(self, doVisionWidget):
        doVisionWidget.setObjectName("doVisionWidget")
        doVisionWidget.setEnabled(True)
        doVisionWidget.resize(398, 599)
        self.verticalLayout = QtWidgets.QVBoxLayout(doVisionWidget)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_6 = QtWidgets.QWidget(doVisionWidget)
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 259))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupRTPipeline_3 = QtWidgets.QGroupBox(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupRTPipeline_3.sizePolicy().hasHeightForWidth())
        self.groupRTPipeline_3.setSizePolicy(sizePolicy)
        self.groupRTPipeline_3.setMinimumSize(QtCore.QSize(138, 241))
        self.groupRTPipeline_3.setMaximumSize(QtCore.QSize(178, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupRTPipeline_3.setFont(font)
        self.groupRTPipeline_3.setObjectName("groupRTPipeline_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupRTPipeline_3)
        self.verticalLayout_6.setContentsMargins(-1, -1, 9, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_5 = QtWidgets.QWidget(self.groupRTPipeline_3)
        self.widget_5.setMaximumSize(QtCore.QSize(150, 50))
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rtstate = QtWidgets.QCheckBox(self.widget_5)
        self.rtstate.setChecked(True)
        self.rtstate.setTristate(True)
        self.rtstate.setObjectName("rtstate")
        self.gridLayout_3.addWidget(self.rtstate, 1, 0, 1, 3)
        self.lRTskip_3 = QtWidgets.QLabel(self.widget_5)
        self.lRTskip_3.setObjectName("lRTskip_3")
        self.gridLayout_3.addWidget(self.lRTskip_3, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.SRCskip_3 = QtWidgets.QSpinBox(self.widget_5)
        self.SRCskip_3.setMinimum(1)
        self.SRCskip_3.setProperty("value", 1)
        self.SRCskip_3.setObjectName("SRCskip_3")
        self.gridLayout_3.addWidget(self.SRCskip_3, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.verticalLayout_6.addWidget(self.widget_5)
        self.line_5 = QtWidgets.QFrame(self.groupRTPipeline_3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_6.addWidget(self.line_5)
        self.rtdetect = QtWidgets.QRadioButton(self.groupRTPipeline_3)
        self.rtdetect.setObjectName("rtdetect")
        self.verticalLayout_6.addWidget(self.rtdetect)
        self.rtfilter = QtWidgets.QCheckBox(self.groupRTPipeline_3)
        self.rtfilter.setObjectName("rtfilter")
        self.verticalLayout_6.addWidget(self.rtfilter)
        self.rtcrop = QtWidgets.QRadioButton(self.groupRTPipeline_3)
        self.rtcrop.setObjectName("rtcrop")
        self.verticalLayout_6.addWidget(self.rtcrop)
        self.rtestimate = QtWidgets.QRadioButton(self.groupRTPipeline_3)
        self.rtestimate.setObjectName("rtestimate")
        self.verticalLayout_6.addWidget(self.rtestimate)
        self.rtrefine = QtWidgets.QRadioButton(self.groupRTPipeline_3)
        self.rtrefine.setObjectName("rtrefine")
        self.verticalLayout_6.addWidget(self.rtrefine)
        self.horizontalLayout_11.addWidget(self.groupRTPipeline_3)
        self.groupPPPipeline_3 = QtWidgets.QGroupBox(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupPPPipeline_3.sizePolicy().hasHeightForWidth())
        self.groupPPPipeline_3.setSizePolicy(sizePolicy)
        self.groupPPPipeline_3.setMinimumSize(QtCore.QSize(151, 241))
        self.groupPPPipeline_3.setMaximumSize(QtCore.QSize(178, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupPPPipeline_3.setFont(font)
        self.groupPPPipeline_3.setObjectName("groupPPPipeline_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupPPPipeline_3)
        self.verticalLayout_7.setContentsMargins(-1, -1, 9, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_7 = QtWidgets.QWidget(self.groupPPPipeline_3)
        self.widget_7.setMaximumSize(QtCore.QSize(150, 50))
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setHorizontalSpacing(6)
        self.gridLayout_7.setVerticalSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 1, 1, 1, 1)
        self.nframes = QtWidgets.QSpinBox(self.widget_7)
        self.nframes.setMaximumSize(QtCore.QSize(50, 16777215))
        self.nframes.setFrame(True)
        self.nframes.setMinimum(0)
        self.nframes.setMaximum(100000)
        self.nframes.setProperty("value", 100)
        self.nframes.setObjectName("nframes")
        self.gridLayout_7.addWidget(self.nframes, 1, 2, 1, 2)
        self.skip = QtWidgets.QSpinBox(self.widget_7)
        self.skip.setMaximumSize(QtCore.QSize(50, 16777215))
        self.skip.setMinimum(1)
        self.skip.setProperty("value", 1)
        self.skip.setObjectName("skip")
        self.gridLayout_7.addWidget(self.skip, 0, 2, 1, 1)
        self.lPPnframes_3 = QtWidgets.QLabel(self.widget_7)
        self.lPPnframes_3.setObjectName("lPPnframes_3")
        self.gridLayout_7.addWidget(self.lPPnframes_3, 1, 0, 1, 1)
        self.lPPskip_3 = QtWidgets.QLabel(self.widget_7)
        self.lPPskip_3.setObjectName("lPPskip_3")
        self.gridLayout_7.addWidget(self.lPPskip_3, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.widget_7)
        self.line_6 = QtWidgets.QFrame(self.groupPPPipeline_3)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_7.addWidget(self.line_6)
        self.ppdetect = QtWidgets.QRadioButton(self.groupPPPipeline_3)
        self.ppdetect.setChecked(False)
        self.ppdetect.setObjectName("ppdetect")
        self.verticalLayout_7.addWidget(self.ppdetect)
        self.ppfilter = QtWidgets.QCheckBox(self.groupPPPipeline_3)
        self.ppfilter.setObjectName("ppfilter")
        self.verticalLayout_7.addWidget(self.ppfilter)
        self.ppcrop = QtWidgets.QRadioButton(self.groupPPPipeline_3)
        self.ppcrop.setObjectName("ppcrop")
        self.verticalLayout_7.addWidget(self.ppcrop)
        self.ppestimate = QtWidgets.QRadioButton(self.groupPPPipeline_3)
        self.ppestimate.setObjectName("ppestimate")
        self.verticalLayout_7.addWidget(self.ppestimate)
        self.pprefine = QtWidgets.QRadioButton(self.groupPPPipeline_3)
        self.pprefine.setChecked(False)
        self.pprefine.setObjectName("pprefine")
        self.verticalLayout_7.addWidget(self.pprefine)
        self.horizontalLayout_11.addWidget(self.groupPPPipeline_3)
        self.verticalLayout.addWidget(self.widget_6)
        self.groupProcess_2 = QtWidgets.QGroupBox(doVisionWidget)
        self.groupProcess_2.setMaximumSize(QtCore.QSize(16777215, 104))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupProcess_2.setFont(font)
        self.groupProcess_2.setObjectName("groupProcess_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupProcess_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(2)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupProcess_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 2, 0, 1, 1)
        self.LOCmaxSize = QtWidgets.QSpinBox(self.groupProcess_2)
        self.LOCmaxSize.setMinimum(0)
        self.LOCmaxSize.setMaximum(100000)
        self.LOCmaxSize.setSingleStep(5)
        self.LOCmaxSize.setProperty("value", 600)
        self.LOCmaxSize.setDisplayIntegerBase(10)
        self.LOCmaxSize.setObjectName("LOCmaxSize")
        self.gridLayout_4.addWidget(self.LOCmaxSize, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupProcess_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 3, 0, 1, 1)
        self.LOCsearchRange = QtWidgets.QDoubleSpinBox(self.groupProcess_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LOCsearchRange.sizePolicy().hasHeightForWidth())
        self.LOCsearchRange.setSizePolicy(sizePolicy)
        self.LOCsearchRange.setPrefix("")
        self.LOCsearchRange.setDecimals(1)
        self.LOCsearchRange.setProperty("value", 5.0)
        self.LOCsearchRange.setObjectName("LOCsearchRange")
        self.gridLayout_4.addWidget(self.LOCsearchRange, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupProcess_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 4, 0, 1, 1)
        self.LOCthreshold = QtWidgets.QDoubleSpinBox(self.groupProcess_2)
        self.LOCthreshold.setSuffix("")
        self.LOCthreshold.setDecimals(2)
        self.LOCthreshold.setMinimum(0.0)
        self.LOCthreshold.setMaximum(1.0)
        self.LOCthreshold.setSingleStep(0.01)
        self.LOCthreshold.setProperty("value", 0.5)
        self.LOCthreshold.setObjectName("LOCthreshold")
        self.gridLayout_4.addWidget(self.LOCthreshold, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupProcess_2)
        self.groupProcess_3 = QtWidgets.QGroupBox(doVisionWidget)
        self.groupProcess_3.setMaximumSize(QtCore.QSize(16777215, 78))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupProcess_3.setFont(font)
        self.groupProcess_3.setObjectName("groupProcess_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupProcess_3)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setHorizontalSpacing(2)
        self.gridLayout_8.setVerticalSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_10 = QtWidgets.QLabel(self.groupProcess_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 3, 1, 1, 1)
        self.FILTdoublestol = QtWidgets.QSpinBox(self.groupProcess_3)
        self.FILTdoublestol.setMinimum(0)
        self.FILTdoublestol.setMaximum(100000)
        self.FILTdoublestol.setSingleStep(5)
        self.FILTdoublestol.setProperty("value", 600)
        self.FILTdoublestol.setDisplayIntegerBase(10)
        self.FILTdoublestol.setObjectName("FILTdoublestol")
        self.gridLayout_8.addWidget(self.FILTdoublestol, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupProcess_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 2, 1, 1, 1)
        self.FILTdoNoEdges = QtWidgets.QCheckBox(self.groupProcess_3)
        self.FILTdoNoEdges.setMaximumSize(QtCore.QSize(20, 16777215))
        self.FILTdoNoEdges.setText("")
        self.FILTdoNoEdges.setObjectName("FILTdoNoEdges")
        self.gridLayout_8.addWidget(self.FILTdoNoEdges, 2, 0, 1, 1)
        self.FILTdoNoDoubles = QtWidgets.QCheckBox(self.groupProcess_3)
        self.FILTdoNoDoubles.setMaximumSize(QtCore.QSize(20, 16777215))
        self.FILTdoNoDoubles.setText("")
        self.FILTdoNoDoubles.setObjectName("FILTdoNoDoubles")
        self.gridLayout_8.addWidget(self.FILTdoNoDoubles, 3, 0, 1, 1)
        self.FILTedgetol = QtWidgets.QSpinBox(self.groupProcess_3)
        self.FILTedgetol.setPrefix("")
        self.FILTedgetol.setMinimum(50)
        self.FILTedgetol.setMaximum(100000)
        self.FILTedgetol.setObjectName("FILTedgetol")
        self.gridLayout_8.addWidget(self.FILTedgetol, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupProcess_3)
        self.groupProcess_4 = QtWidgets.QGroupBox(doVisionWidget)
        self.groupProcess_4.setMaximumSize(QtCore.QSize(16777215, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupProcess_4.setFont(font)
        self.groupProcess_4.setObjectName("groupProcess_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupProcess_4)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setHorizontalSpacing(2)
        self.gridLayout_9.setVerticalSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.bLink = QtWidgets.QCheckBox(self.groupProcess_4)
        self.bLink.setTristate(True)
        self.bLink.setObjectName("bLink")
        self.gridLayout_9.addWidget(self.bLink, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupProcess_4)
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupProcess_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 3, 0, 1, 1)
        self.linkTol = QtWidgets.QSpinBox(self.groupProcess_4)
        self.linkTol.setMinimum(0)
        self.linkTol.setMaximum(100000)
        self.linkTol.setSingleStep(5)
        self.linkTol.setProperty("value", 600)
        self.linkTol.setDisplayIntegerBase(10)
        self.linkTol.setObjectName("linkTol")
        self.gridLayout_9.addWidget(self.linkTol, 3, 1, 1, 1)
        self.memory = QtWidgets.QDoubleSpinBox(self.groupProcess_4)
        self.memory.setDecimals(0)
        self.memory.setMinimum(1.0)
        self.memory.setMaximum(100.0)
        self.memory.setProperty("value", 2.0)
        self.memory.setObjectName("memory")
        self.gridLayout_9.addWidget(self.memory, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupProcess_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupProcess_4)
        self.frame = QtWidgets.QFrame(doVisionWidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SRC_paused = QtWidgets.QCheckBox(self.frame)
        self.SRC_paused.setObjectName("SRC_paused")
        self.horizontalLayout_3.addWidget(self.SRC_paused)
        self.bstart = QtWidgets.QPushButton(self.frame)
        self.bstart.setObjectName("bstart")
        self.horizontalLayout_3.addWidget(self.bstart)
        self.bstop = QtWidgets.QPushButton(self.frame)
        self.bstop.setEnabled(False)
        self.bstop.setObjectName("bstop")
        self.horizontalLayout_3.addWidget(self.bstop)
        self.bpause = QtWidgets.QPushButton(self.frame)
        self.bpause.setObjectName("bpause")
        self.horizontalLayout_3.addWidget(self.bpause)
        self.bshutdown = QtWidgets.QPushButton(self.frame)
        self.bshutdown.setObjectName("bshutdown")
        self.horizontalLayout_3.addWidget(self.bshutdown)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(doVisionWidget)
        QtCore.QMetaObject.connectSlotsByName(doVisionWidget)

    def retranslateUi(self, doVisionWidget):
        _translate = QtCore.QCoreApplication.translate
        doVisionWidget.setWindowTitle(_translate("doVisionWidget", "Form"))
        self.groupRTPipeline_3.setTitle(_translate("doVisionWidget", "Real Time"))
        self.rtstate.setStatusTip(_translate("doVisionWidget", "Deep neural network pipeline with precision holographic characterization"))
        self.rtstate.setText(_translate("doVisionWidget", "Enabled   "))
        self.lRTskip_3.setText(_translate("doVisionWidget", "skip"))
        self.rtdetect.setStatusTip(_translate("doVisionWidget", "Deep neural network (x, y) feature detection"))
        self.rtdetect.setText(_translate("doVisionWidget", "Detect"))
        self.rtfilter.setStatusTip(_translate("doVisionWidget", "Deep neural network (x, y) feature detection"))
        self.rtfilter.setText(_translate("doVisionWidget", "Filter"))
        self.rtcrop.setText(_translate("doVisionWidget", "Get Features"))
        self.rtestimate.setStatusTip(_translate("doVisionWidget", "Deep neural network (x, y, z) feature detection and holographic characterization"))
        self.rtestimate.setText(_translate("doVisionWidget", "Estimate"))
        self.rtrefine.setStatusTip(_translate("doVisionWidget", "Deep neural network pipeline with precision holographic characterization"))
        self.rtrefine.setText(_translate("doVisionWidget", "Refine"))
        self.groupPPPipeline_3.setTitle(_translate("doVisionWidget", "Post-Process"))
        self.lPPnframes_3.setText(_translate("doVisionWidget", "nframes"))
        self.lPPskip_3.setText(_translate("doVisionWidget", "skip"))
        self.ppdetect.setStatusTip(_translate("doVisionWidget", "Deep neural network (x, y) feature detection"))
        self.ppdetect.setText(_translate("doVisionWidget", "Detect"))
        self.ppfilter.setText(_translate("doVisionWidget", "Filter"))
        self.ppcrop.setText(_translate("doVisionWidget", "Get Features"))
        self.ppestimate.setStatusTip(_translate("doVisionWidget", "Deep neural network (x, y, z) feature detection and holographic characterization"))
        self.ppestimate.setText(_translate("doVisionWidget", "Estimate"))
        self.pprefine.setStatusTip(_translate("doVisionWidget", "Deep neural network pipeline with precision holographic characterization"))
        self.pprefine.setText(_translate("doVisionWidget", "Refine"))
        self.groupProcess_2.setTitle(_translate("doVisionWidget", "Detection"))
        self.label_5.setStatusTip(_translate("doVisionWidget", "Confidence threshold for detections. Throw away features detected below this confidence."))
        self.label_5.setText(_translate("doVisionWidget", "Confidence"))
        self.LOCmaxSize.setStatusTip(_translate("doVisionWidget", "Maximum edge length that is considered a detection. Useful for real-time processing and eliminating artifacts."))
        self.LOCmaxSize.setSuffix(_translate("doVisionWidget", " pixels"))
        self.label_6.setStatusTip(_translate("doVisionWidget", "Maximum edge length that is considered a detection. Useful for real-time processing and eliminating artifacts."))
        self.label_6.setText(_translate("doVisionWidget", "Max size"))
        self.LOCsearchRange.setStatusTip(_translate("doVisionWidget", "Maximum distance features can move between frames in order to be linked to the same Trajectory."))
        self.LOCsearchRange.setSuffix(_translate("doVisionWidget", " pixels"))
        self.label_2.setStatusTip(_translate("doVisionWidget", "Maximum distance features can move between frames in order to be linked to the same Trajectory"))
        self.label_2.setText(_translate("doVisionWidget", "Search range"))
        self.LOCthreshold.setStatusTip(_translate("doVisionWidget", "Confidence threshold for detections. Throw away features detected below this confidence."))
        self.groupProcess_3.setTitle(_translate("doVisionWidget", "Filtering"))
        self.label_10.setStatusTip(_translate("doVisionWidget", "Maximum edge length that is considered a detection. Useful for real-time processing and eliminating artifacts."))
        self.label_10.setText(_translate("doVisionWidget", "Doubles Tol"))
        self.FILTdoublestol.setStatusTip(_translate("doVisionWidget", "Maximum edge length that is considered a detection. Useful for real-time processing and eliminating artifacts."))
        self.FILTdoublestol.setSuffix(_translate("doVisionWidget", " pixels"))
        self.label_9.setStatusTip(_translate("doVisionWidget", "Confidence threshold for detections. Throw away features detected below this confidence."))
        self.label_9.setText(_translate("doVisionWidget", "Edge Tol"))
        self.FILTedgetol.setStatusTip(_translate("doVisionWidget", "Confidence threshold for detections. Throw away features detected below this confidence."))
        self.FILTedgetol.setSuffix(_translate("doVisionWidget", " pixels"))
        self.groupProcess_4.setTitle(_translate("doVisionWidget", "Trajectories"))
        self.bLink.setText(_translate("doVisionWidget", "CheckBox"))
        self.label.setText(_translate("doVisionWidget", "Link"))
        self.label_11.setStatusTip(_translate("doVisionWidget", "Maximum edge length that is considered a detection. Useful for real-time processing and eliminating artifacts."))
        self.label_11.setText(_translate("doVisionWidget", "Link Tol"))
        self.linkTol.setStatusTip(_translate("doVisionWidget", "Maximum edge length that is considered a detection. Useful for real-time processing and eliminating artifacts."))
        self.linkTol.setSuffix(_translate("doVisionWidget", " pixels"))
        self.memory.setStatusTip(_translate("doVisionWidget", "Confidence threshold for detections. Throw away features detected below this confidence."))
        self.memory.setSuffix(_translate("doVisionWidget", " frames"))
        self.label_3.setText(_translate("doVisionWidget", "Memory"))
        self.SRC_paused.setText(_translate("doVisionWidget", "Read Frames"))
        self.bstart.setText(_translate("doVisionWidget", "Start"))
        self.bstop.setText(_translate("doVisionWidget", "Stop"))
        self.bpause.setText(_translate("doVisionWidget", "Pause"))
        self.bshutdown.setText(_translate("doVisionWidget", "Shut Down"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    doVisionWidget = QtWidgets.QWidget()
    ui = Ui_doVisionWidget()
    ui.setupUi(doVisionWidget)
    doVisionWidget.show()
    sys.exit(app.exec_())

