# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QProscan_UI.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QProscan(object):
    def setupUi(self, QProscan):
        QProscan.setObjectName("QProscan")
        QProscan.resize(324, 48)
        self.gridLayout = QtWidgets.QGridLayout(QProscan)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.labelX = QtWidgets.QLabel(QProscan)
        self.labelX.setAlignment(QtCore.Qt.AlignCenter)
        self.labelX.setObjectName("labelX")
        self.gridLayout.addWidget(self.labelX, 0, 0, 1, 1)
        self.labelY = QtWidgets.QLabel(QProscan)
        self.labelY.setAlignment(QtCore.Qt.AlignCenter)
        self.labelY.setObjectName("labelY")
        self.gridLayout.addWidget(self.labelY, 0, 1, 1, 1)
        self.labelZ = QtWidgets.QLabel(QProscan)
        self.labelZ.setAlignment(QtCore.Qt.AlignCenter)
        self.labelZ.setObjectName("labelZ")
        self.gridLayout.addWidget(self.labelZ, 0, 2, 1, 1)
        self.lcdX = QtWidgets.QLCDNumber(QProscan)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lcdX.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lcdX.setFont(font)
        self.lcdX.setAutoFillBackground(True)
        self.lcdX.setNumDigits(9)
        self.lcdX.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdX.setObjectName("lcdX")
        self.gridLayout.addWidget(self.lcdX, 1, 0, 1, 1)
        self.lcdY = QtWidgets.QLCDNumber(QProscan)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lcdY.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lcdY.setFont(font)
        self.lcdY.setAutoFillBackground(True)
        self.lcdY.setNumDigits(9)
        self.lcdY.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdY.setObjectName("lcdY")
        self.gridLayout.addWidget(self.lcdY, 1, 1, 1, 1)
        self.lcdZ = QtWidgets.QLCDNumber(QProscan)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lcdZ.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lcdZ.setFont(font)
        self.lcdZ.setAutoFillBackground(True)
        self.lcdZ.setNumDigits(9)
        self.lcdZ.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdZ.setObjectName("lcdZ")
        self.gridLayout.addWidget(self.lcdZ, 1, 2, 1, 1)

        self.retranslateUi(QProscan)
        QtCore.QMetaObject.connectSlotsByName(QProscan)

    def retranslateUi(self, QProscan):
        _translate = QtCore.QCoreApplication.translate
        QProscan.setWindowTitle(_translate("QProscan", "QProscan"))
        self.labelX.setText(_translate("QProscan", "x [µm]"))
        self.labelY.setText(_translate("QProscan", "y [µm]"))
        self.labelZ.setText(_translate("QProscan", "z [µm]"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QProscan = QtWidgets.QWidget()
    ui = Ui_QProscan()
    ui.setupUi(QProscan)
    QProscan.show()
    sys.exit(app.exec_())
