# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QCGHWidget.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QCGHWidget(object):
    def setupUi(self, QCGHWidget):
        QCGHWidget.setObjectName("QCGHWidget")
        QCGHWidget.resize(220, 333)
        self.verticalLayout = QtWidgets.QVBoxLayout(QCGHWidget)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupInstrument = QtWidgets.QGroupBox(QCGHWidget)
        self.groupInstrument.setStatusTip("")
        self.groupInstrument.setObjectName("groupInstrument")
        self.formLayout = QtWidgets.QFormLayout(self.groupInstrument)
        self.formLayout.setContentsMargins(2, 2, 2, 2)
        self.formLayout.setSpacing(2)
        self.formLayout.setObjectName("formLayout")
        self.labelWavelength = QtWidgets.QLabel(self.groupInstrument)
        self.labelWavelength.setObjectName("labelWavelength")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelWavelength)
        self.wavelength = QtWidgets.QDoubleSpinBox(self.groupInstrument)
        self.wavelength.setDecimals(3)
        self.wavelength.setMaximum(2.0)
        self.wavelength.setSingleStep(0.001)
        self.wavelength.setProperty("value", 1.064)
        self.wavelength.setObjectName("wavelength")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.wavelength)
        self.labelRefractiveIndex = QtWidgets.QLabel(self.groupInstrument)
        self.labelRefractiveIndex.setObjectName("labelRefractiveIndex")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelRefractiveIndex)
        self.refractiveIndex = QtWidgets.QDoubleSpinBox(self.groupInstrument)
        self.refractiveIndex.setDecimals(3)
        self.refractiveIndex.setMinimum(1.0)
        self.refractiveIndex.setMaximum(2.0)
        self.refractiveIndex.setSingleStep(0.001)
        self.refractiveIndex.setProperty("value", 1.34)
        self.refractiveIndex.setObjectName("refractiveIndex")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.refractiveIndex)
        self.labelMagnification = QtWidgets.QLabel(self.groupInstrument)
        self.labelMagnification.setObjectName("labelMagnification")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelMagnification)
        self.magnification = QtWidgets.QDoubleSpinBox(self.groupInstrument)
        self.magnification.setDecimals(3)
        self.magnification.setMaximum(1.0)
        self.magnification.setSingleStep(0.001)
        self.magnification.setProperty("value", 0.048)
        self.magnification.setObjectName("magnification")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.magnification)
        self.labelFocalLength = QtWidgets.QLabel(self.groupInstrument)
        self.labelFocalLength.setObjectName("labelFocalLength")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelFocalLength)
        self.focalLength = QtWidgets.QDoubleSpinBox(self.groupInstrument)
        self.focalLength.setDecimals(0)
        self.focalLength.setMinimum(100.0)
        self.focalLength.setMaximum(400.0)
        self.focalLength.setSingleStep(10.0)
        self.focalLength.setProperty("value", 200.0)
        self.focalLength.setObjectName("focalLength")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.focalLength)
        self.verticalLayout.addWidget(self.groupInstrument)
        self.groupCameraPlane = QtWidgets.QGroupBox(QCGHWidget)
        self.groupCameraPlane.setObjectName("groupCameraPlane")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupCameraPlane)
        self.formLayout_2.setContentsMargins(2, 2, 2, 2)
        self.formLayout_2.setSpacing(2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelXc = QtWidgets.QLabel(self.groupCameraPlane)
        self.labelXc.setObjectName("labelXc")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelXc)
        self.xc = QtWidgets.QDoubleSpinBox(self.groupCameraPlane)
        self.xc.setDecimals(1)
        self.xc.setMaximum(2000.0)
        self.xc.setSingleStep(10000000.0)
        self.xc.setProperty("value", 300.0)
        self.xc.setObjectName("xc")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.xc)
        self.labelYc = QtWidgets.QLabel(self.groupCameraPlane)
        self.labelYc.setObjectName("labelYc")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelYc)
        self.yc = QtWidgets.QDoubleSpinBox(self.groupCameraPlane)
        self.yc.setDecimals(1)
        self.yc.setMaximum(2000.0)
        self.yc.setSingleStep(10.0)
        self.yc.setProperty("value", 300.0)
        self.yc.setObjectName("yc")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.yc)
        self.labelZc = QtWidgets.QLabel(self.groupCameraPlane)
        self.labelZc.setObjectName("labelZc")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelZc)
        self.zc = QtWidgets.QDoubleSpinBox(self.groupCameraPlane)
        self.zc.setDecimals(1)
        self.zc.setMinimum(-900.0)
        self.zc.setMaximum(900.0)
        self.zc.setObjectName("zc")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.zc)
        self.labelThetac = QtWidgets.QLabel(self.groupCameraPlane)
        self.labelThetac.setObjectName("labelThetac")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelThetac)
        self.thetac = QtWidgets.QDoubleSpinBox(self.groupCameraPlane)
        self.thetac.setDecimals(1)
        self.thetac.setMinimum(-180.0)
        self.thetac.setMaximum(180.0)
        self.thetac.setObjectName("thetac")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.thetac)
        self.verticalLayout.addWidget(self.groupCameraPlane)
        self.groupSLMPlane = QtWidgets.QGroupBox(QCGHWidget)
        self.groupSLMPlane.setObjectName("groupSLMPlane")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupSLMPlane)
        self.formLayout_3.setContentsMargins(2, 2, 2, 2)
        self.formLayout_3.setSpacing(2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.labelXs = QtWidgets.QLabel(self.groupSLMPlane)
        self.labelXs.setObjectName("labelXs")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelXs)
        self.xs = QtWidgets.QDoubleSpinBox(self.groupSLMPlane)
        self.xs.setDecimals(1)
        self.xs.setMaximum(3000.0)
        self.xs.setSingleStep(10.0)
        self.xs.setProperty("value", 300.0)
        self.xs.setObjectName("xs")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.xs)
        self.labelYs = QtWidgets.QLabel(self.groupSLMPlane)
        self.labelYs.setObjectName("labelYs")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelYs)
        self.ys = QtWidgets.QDoubleSpinBox(self.groupSLMPlane)
        self.ys.setDecimals(1)
        self.ys.setMaximum(3000.0)
        self.ys.setSingleStep(10.0)
        self.ys.setProperty("value", 300.0)
        self.ys.setObjectName("ys")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ys)
        self.labelPhis = QtWidgets.QLabel(self.groupSLMPlane)
        self.labelPhis.setObjectName("labelPhis")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelPhis)
        self.phis = QtWidgets.QDoubleSpinBox(self.groupSLMPlane)
        self.phis.setDecimals(1)
        self.phis.setMaximum(45.0)
        self.phis.setProperty("value", 8.0)
        self.phis.setObjectName("phis")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.phis)
        self.verticalLayout.addWidget(self.groupSLMPlane)

        self.retranslateUi(QCGHWidget)
        QtCore.QMetaObject.connectSlotsByName(QCGHWidget)
        QCGHWidget.setTabOrder(self.wavelength, self.refractiveIndex)
        QCGHWidget.setTabOrder(self.refractiveIndex, self.magnification)
        QCGHWidget.setTabOrder(self.magnification, self.focalLength)
        QCGHWidget.setTabOrder(self.focalLength, self.xc)
        QCGHWidget.setTabOrder(self.xc, self.yc)
        QCGHWidget.setTabOrder(self.yc, self.thetac)
        QCGHWidget.setTabOrder(self.thetac, self.zc)
        QCGHWidget.setTabOrder(self.zc, self.xs)
        QCGHWidget.setTabOrder(self.xs, self.ys)
        QCGHWidget.setTabOrder(self.ys, self.phis)

    def retranslateUi(self, QCGHWidget):
        _translate = QtCore.QCoreApplication.translate
        QCGHWidget.setWindowTitle(_translate("QCGHWidget", "Form"))
        self.groupInstrument.setTitle(_translate("QCGHWidget", "Instrument"))
        self.labelWavelength.setText(_translate("QCGHWidget", "Wavelength"))
        self.wavelength.setStatusTip(_translate("QCGHWidget", "Instrument: Vacuum wavelength of trapping laser"))
        self.wavelength.setSuffix(_translate("QCGHWidget", " μm"))
        self.labelRefractiveIndex.setText(_translate("QCGHWidget", "Refractive index"))
        self.refractiveIndex.setStatusTip(_translate("QCGHWidget", "Instrument: Refractive index of medium"))
        self.labelMagnification.setText(_translate("QCGHWidget", "Magnification"))
        self.magnification.setStatusTip(_translate("QCGHWidget", "Instrument: Magnification of microscope"))
        self.magnification.setSuffix(_translate("QCGHWidget", " μm/pixel"))
        self.labelFocalLength.setText(_translate("QCGHWidget", "Focal length"))
        self.focalLength.setStatusTip(_translate("QCGHWidget", "Instrument: Focal length of objective lens"))
        self.focalLength.setSuffix(_translate("QCGHWidget", " μm"))
        self.groupCameraPlane.setTitle(_translate("QCGHWidget", "Camera Plane"))
        self.labelXc.setText(_translate("QCGHWidget", "xc"))
        self.xc.setStatusTip(_translate("QCGHWidget", "Camera: x coordinate of optical axis"))
        self.xc.setSuffix(_translate("QCGHWidget", " pixel"))
        self.labelYc.setText(_translate("QCGHWidget", "yc"))
        self.yc.setStatusTip(_translate("QCGHWidget", "Camera: y coordinate of optical axis"))
        self.yc.setSuffix(_translate("QCGHWidget", " pixel"))
        self.labelZc.setText(_translate("QCGHWidget", "zc"))
        self.zc.setStatusTip(_translate("QCGHWidget", "Camera: Axial displacement of trapping plane from focal plane"))
        self.zc.setSuffix(_translate("QCGHWidget", " pixel"))
        self.labelThetac.setText(_translate("QCGHWidget", "θc"))
        self.thetac.setStatusTip(_translate("QCGHWidget", "Camera: Orientation relative to SLM"))
        self.thetac.setSuffix(_translate("QCGHWidget", "°"))
        self.groupSLMPlane.setTitle(_translate("QCGHWidget", "SLM Plane"))
        self.labelXs.setText(_translate("QCGHWidget", "xs"))
        self.xs.setStatusTip(_translate("QCGHWidget", "SLM: x coordinate of optical axis on SLM"))
        self.xs.setSuffix(_translate("QCGHWidget", " pixel"))
        self.labelYs.setText(_translate("QCGHWidget", "ys"))
        self.ys.setStatusTip(_translate("QCGHWidget", "SLM: y coordinate of optical axis on SLM"))
        self.ys.setSuffix(_translate("QCGHWidget", " pixel"))
        self.labelPhis.setText(_translate("QCGHWidget", "φs"))
        self.phis.setStatusTip(_translate("QCGHWidget", "SLM: Tilt relative to optical axis"))
        self.phis.setSuffix(_translate("QCGHWidget", "°"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QCGHWidget = QtWidgets.QWidget()
    ui = Ui_QCGHWidget()
    ui.setupUi(QCGHWidget)
    QCGHWidget.show()
    sys.exit(app.exec_())
