# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasks/vision/doVisionWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_doVisionWidget(object):
    def setupUi(self, doVisionWidget):
        doVisionWidget.setObjectName("doVisionWidget")
        doVisionWidget.resize(471, 538)
        self.gridLayout = QtWidgets.QGridLayout(doVisionWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupDetect = QtWidgets.QGroupBox(doVisionWidget)
        self.groupDetect.setMaximumSize(QtCore.QSize(16777215, 104))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupDetect.setFont(font)
        self.groupDetect.setObjectName("groupDetect")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupDetect)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(2)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.LOCthreshold = QtWidgets.QDoubleSpinBox(self.groupDetect)
        self.LOCthreshold.setSuffix("")
        self.LOCthreshold.setDecimals(2)
        self.LOCthreshold.setMinimum(0.0)
        self.LOCthreshold.setMaximum(1.0)
        self.LOCthreshold.setSingleStep(0.01)
        self.LOCthreshold.setProperty("value", 0.5)
        self.LOCthreshold.setObjectName("LOCthreshold")
        self.gridLayout_5.addWidget(self.LOCthreshold, 2, 1, 1, 1)
        self.LOCsearchRange = QtWidgets.QDoubleSpinBox(self.groupDetect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LOCsearchRange.sizePolicy().hasHeightForWidth())
        self.LOCsearchRange.setSizePolicy(sizePolicy)
        self.LOCsearchRange.setPrefix("")
        self.LOCsearchRange.setDecimals(1)
        self.LOCsearchRange.setProperty("value", 5.0)
        self.LOCsearchRange.setObjectName("LOCsearchRange")
        self.gridLayout_5.addWidget(self.LOCsearchRange, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupDetect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupDetect)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 3, 0, 1, 1)
        self.LOCmaxSize = QtWidgets.QSpinBox(self.groupDetect)
        self.LOCmaxSize.setMinimum(0)
        self.LOCmaxSize.setMaximum(100000)
        self.LOCmaxSize.setSingleStep(5)
        self.LOCmaxSize.setProperty("value", 600)
        self.LOCmaxSize.setDisplayIntegerBase(10)
        self.LOCmaxSize.setObjectName("LOCmaxSize")
        self.gridLayout_5.addWidget(self.LOCmaxSize, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupDetect)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupDetect, 7, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(doVisionWidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, 9)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.skip = QtWidgets.QSpinBox(self.groupBox)
        self.skip.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.skip.setMinimum(1)
        self.skip.setProperty("value", 5)
        self.skip.setObjectName("skip")
        self.gridLayout_2.addWidget(self.skip, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.continuous = QtWidgets.QCheckBox(self.groupBox)
        self.continuous.setChecked(True)
        self.continuous.setObjectName("continuous")
        self.gridLayout_2.addWidget(self.continuous, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.nframes = QtWidgets.QSpinBox(self.groupBox)
        self.nframes.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.nframes.setPrefix("")
        self.nframes.setMinimum(1)
        self.nframes.setMaximum(100000)
        self.nframes.setProperty("value", 5)
        self.nframes.setObjectName("nframes")
        self.gridLayout_2.addWidget(self.nframes, 0, 1, 1, 1)
        self._paused = QtWidgets.QCheckBox(self.groupBox)
        self._paused.setObjectName("_paused")
        self.gridLayout_2.addWidget(self._paused, 2, 0, 1, 1)
        self.bstart = QtWidgets.QPushButton(self.groupBox)
        self.bstart.setObjectName("bstart")
        self.gridLayout_2.addWidget(self.bstart, 3, 0, 1, 1)
        self.bstop = QtWidgets.QPushButton(self.groupBox)
        self.bstop.setEnabled(False)
        self.bstop.setObjectName("bstop")
        self.gridLayout_2.addWidget(self.bstop, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupFilter = QtWidgets.QGroupBox(doVisionWidget)
        self.groupFilter.setMaximumSize(QtCore.QSize(16777215, 78))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupFilter.setFont(font)
        self.groupFilter.setCheckable(False)
        self.groupFilter.setObjectName("groupFilter")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupFilter)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setHorizontalSpacing(2)
        self.gridLayout_8.setVerticalSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_10 = QtWidgets.QLabel(self.groupFilter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 3, 1, 1, 1)
        self.doublestol = QtWidgets.QSpinBox(self.groupFilter)
        self.doublestol.setMinimum(0)
        self.doublestol.setMaximum(100000)
        self.doublestol.setSingleStep(5)
        self.doublestol.setProperty("value", 600)
        self.doublestol.setDisplayIntegerBase(10)
        self.doublestol.setObjectName("doublestol")
        self.gridLayout_8.addWidget(self.doublestol, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupFilter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 2, 1, 1, 1)
        self.doNoEdges = QtWidgets.QCheckBox(self.groupFilter)
        self.doNoEdges.setMaximumSize(QtCore.QSize(20, 16777215))
        self.doNoEdges.setText("")
        self.doNoEdges.setObjectName("doNoEdges")
        self.gridLayout_8.addWidget(self.doNoEdges, 2, 0, 1, 1)
        self.doNoDoubles = QtWidgets.QCheckBox(self.groupFilter)
        self.doNoDoubles.setMaximumSize(QtCore.QSize(20, 16777215))
        self.doNoDoubles.setText("")
        self.doNoDoubles.setObjectName("doNoDoubles")
        self.gridLayout_8.addWidget(self.doNoDoubles, 3, 0, 1, 1)
        self.edgetol = QtWidgets.QSpinBox(self.groupFilter)
        self.edgetol.setPrefix("")
        self.edgetol.setMinimum(50)
        self.edgetol.setMaximum(100000)
        self.edgetol.setObjectName("edgetol")
        self.gridLayout_8.addWidget(self.edgetol, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.groupFilter, 8, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(doVisionWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rtenabled = QtWidgets.QGroupBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rtenabled.sizePolicy().hasHeightForWidth())
        self.rtenabled.setSizePolicy(sizePolicy)
        self.rtenabled.setMinimumSize(QtCore.QSize(0, 0))
        self.rtenabled.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rtenabled.setFont(font)
        self.rtenabled.setCheckable(True)
        self.rtenabled.setObjectName("rtenabled")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.rtenabled)
        self.verticalLayout_7.setContentsMargins(-1, 0, 9, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.rtdetect = QtWidgets.QRadioButton(self.rtenabled)
        self.rtdetect.setObjectName("rtdetect")
        self.verticalLayout_7.addWidget(self.rtdetect)
        self.rtfilt = QtWidgets.QRadioButton(self.rtenabled)
        self.rtfilt.setObjectName("rtfilt")
        self.verticalLayout_7.addWidget(self.rtfilt)
        self.rtcrop = QtWidgets.QRadioButton(self.rtenabled)
        self.rtcrop.setObjectName("rtcrop")
        self.verticalLayout_7.addWidget(self.rtcrop)
        self.rtestimate = QtWidgets.QRadioButton(self.rtenabled)
        self.rtestimate.setObjectName("rtestimate")
        self.verticalLayout_7.addWidget(self.rtestimate)
        self.rtrefine = QtWidgets.QRadioButton(self.rtenabled)
        self.rtrefine.setMinimumSize(QtCore.QSize(0, 0))
        self.rtrefine.setObjectName("rtrefine")
        self.verticalLayout_7.addWidget(self.rtrefine)
        self.horizontalLayout.addWidget(self.rtenabled)
        self.ppenabled = QtWidgets.QGroupBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ppenabled.sizePolicy().hasHeightForWidth())
        self.ppenabled.setSizePolicy(sizePolicy)
        self.ppenabled.setMinimumSize(QtCore.QSize(0, 0))
        self.ppenabled.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ppenabled.setFont(font)
        self.ppenabled.setCheckable(True)
        self.ppenabled.setChecked(True)
        self.ppenabled.setObjectName("ppenabled")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.ppenabled)
        self.verticalLayout_8.setContentsMargins(-1, 0, 9, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ppdetect = QtWidgets.QRadioButton(self.ppenabled)
        self.ppdetect.setChecked(False)
        self.ppdetect.setObjectName("ppdetect")
        self.verticalLayout_8.addWidget(self.ppdetect)
        self.ppfilt = QtWidgets.QRadioButton(self.ppenabled)
        self.ppfilt.setObjectName("ppfilt")
        self.verticalLayout_8.addWidget(self.ppfilt)
        self.ppcrop = QtWidgets.QRadioButton(self.ppenabled)
        self.ppcrop.setObjectName("ppcrop")
        self.verticalLayout_8.addWidget(self.ppcrop)
        self.ppestimate = QtWidgets.QRadioButton(self.ppenabled)
        self.ppestimate.setObjectName("ppestimate")
        self.verticalLayout_8.addWidget(self.ppestimate)
        self.pprefine = QtWidgets.QRadioButton(self.ppenabled)
        self.pprefine.setChecked(False)
        self.pprefine.setObjectName("pprefine")
        self.verticalLayout_8.addWidget(self.pprefine)
        self.horizontalLayout.addWidget(self.ppenabled)
        self.gridLayout.addWidget(self.groupBox_2, 2, 0, 1, 2)

        self.retranslateUi(doVisionWidget)
        QtCore.QMetaObject.connectSlotsByName(doVisionWidget)

    def retranslateUi(self, doVisionWidget):
        _translate = QtCore.QCoreApplication.translate
        doVisionWidget.setWindowTitle(_translate("doVisionWidget", "Form"))
        self.groupDetect.setTitle(_translate("doVisionWidget", "Detection"))
        self.LOCthreshold.setStatusTip(_translate("doVisionWidget", "Confidence threshold for detections. Throw away features detected below this confidence."))
        self.LOCsearchRange.setStatusTip(_translate("doVisionWidget", "Maximum distance features can move between frames in order to be linked to the same Trajectory."))
        self.LOCsearchRange.setSuffix(_translate("doVisionWidget", " pixels"))
        self.label_3.setStatusTip(_translate("doVisionWidget", "Maximum distance features can move between frames in order to be linked to the same Trajectory"))
        self.label_3.setText(_translate("doVisionWidget", "Search range"))
        self.label_8.setStatusTip(_translate("doVisionWidget", "Maximum edge length that is considered a detection. Useful for real-time processing and eliminating artifacts."))
        self.label_8.setText(_translate("doVisionWidget", "Max size"))
        self.LOCmaxSize.setStatusTip(_translate("doVisionWidget", "Maximum edge length that is considered a detection. Useful for real-time processing and eliminating artifacts."))
        self.LOCmaxSize.setSuffix(_translate("doVisionWidget", " pixels"))
        self.label_7.setStatusTip(_translate("doVisionWidget", "Confidence threshold for detections. Throw away features detected below this confidence."))
        self.label_7.setText(_translate("doVisionWidget", "Confidence"))
        self.groupBox.setTitle(_translate("doVisionWidget", "Tracking"))
        self.skip.setSpecialValueText(_translate("doVisionWidget", "every Frame"))
        self.skip.setSuffix(_translate("doVisionWidget", " Frames"))
        self.skip.setPrefix(_translate("doVisionWidget", "every "))
        self.label.setText(_translate("doVisionWidget", "Do real-time analysis"))
        self.continuous.setText(_translate("doVisionWidget", "Continuous Capture"))
        self.label_4.setText(_translate("doVisionWidget", "Do analysis for "))
        self.nframes.setSpecialValueText(_translate("doVisionWidget", "1 Frame"))
        self.nframes.setSuffix(_translate("doVisionWidget", " Frames"))
        self._paused.setText(_translate("doVisionWidget", "Tracking Paused"))
        self.bstart.setText(_translate("doVisionWidget", "Start Tracking"))
        self.bstop.setText(_translate("doVisionWidget", "Stop Tracking"))
        self.groupFilter.setTitle(_translate("doVisionWidget", "Filtering"))
        self.label_10.setStatusTip(_translate("doVisionWidget", "Maximum edge length that is considered a detection. Useful for real-time processing and eliminating artifacts."))
        self.label_10.setText(_translate("doVisionWidget", "Doubles Tol"))
        self.doublestol.setStatusTip(_translate("doVisionWidget", "Maximum edge length that is considered a detection. Useful for real-time processing and eliminating artifacts."))
        self.doublestol.setSuffix(_translate("doVisionWidget", " pixels"))
        self.label_9.setStatusTip(_translate("doVisionWidget", "Confidence threshold for detections. Throw away features detected below this confidence."))
        self.label_9.setText(_translate("doVisionWidget", "Edge Tol"))
        self.edgetol.setStatusTip(_translate("doVisionWidget", "Confidence threshold for detections. Throw away features detected below this confidence."))
        self.edgetol.setSuffix(_translate("doVisionWidget", " pixels"))
        self.groupBox_2.setTitle(_translate("doVisionWidget", "Configure Tracking"))
        self.rtenabled.setTitle(_translate("doVisionWidget", "Real Time"))
        self.rtdetect.setStatusTip(_translate("doVisionWidget", "Deep neural network (x, y) feature detection"))
        self.rtdetect.setText(_translate("doVisionWidget", "Detect"))
        self.rtfilt.setStatusTip(_translate("doVisionWidget", "Deep neural network (x, y) feature detection"))
        self.rtfilt.setText(_translate("doVisionWidget", "Filter"))
        self.rtcrop.setText(_translate("doVisionWidget", "Crop Features"))
        self.rtestimate.setStatusTip(_translate("doVisionWidget", "Deep neural network (x, y, z) feature detection and holographic characterization"))
        self.rtestimate.setText(_translate("doVisionWidget", "Estimate"))
        self.rtrefine.setStatusTip(_translate("doVisionWidget", "Deep neural network pipeline with precision holographic characterization"))
        self.rtrefine.setText(_translate("doVisionWidget", "Refine"))
        self.ppenabled.setTitle(_translate("doVisionWidget", "Post-Process"))
        self.ppdetect.setStatusTip(_translate("doVisionWidget", "Deep neural network (x, y) feature detection"))
        self.ppdetect.setText(_translate("doVisionWidget", "Detect"))
        self.ppfilt.setText(_translate("doVisionWidget", "Filter"))
        self.ppcrop.setText(_translate("doVisionWidget", "Crop Features"))
        self.ppestimate.setStatusTip(_translate("doVisionWidget", "Deep neural network (x, y, z) feature detection and holographic characterization"))
        self.ppestimate.setText(_translate("doVisionWidget", "Estimate"))
        self.pprefine.setStatusTip(_translate("doVisionWidget", "Deep neural network pipeline with precision holographic characterization"))
        self.pprefine.setText(_translate("doVisionWidget", "Refine"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    doVisionWidget = QtWidgets.QWidget()
    ui = Ui_doVisionWidget()
    ui.setupUi(doVisionWidget)
    doVisionWidget.show()
    sys.exit(app.exec_())

