# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasks/vision/toVisionWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_toVisionWidget(object):
    def setupUi(self, toVisionWidget):
        toVisionWidget.setObjectName("toVisionWidget")
        toVisionWidget.resize(386, 500)
        toVisionWidget.setMinimumSize(QtCore.QSize(0, 500))
        self.gridLayout = QtWidgets.QGridLayout(toVisionWidget)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(toVisionWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.FramesView = QtWidgets.QListView(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.FramesView.sizePolicy().hasHeightForWidth())
        self.FramesView.setSizePolicy(sizePolicy)
        self.FramesView.setObjectName("FramesView")
        self.gridLayout_3.addWidget(self.FramesView, 0, 0, 1, 1)
        self.SelectedFramesView = QtWidgets.QTableView(self.groupBox_2)
        self.SelectedFramesView.setObjectName("SelectedFramesView")
        self.gridLayout_3.addWidget(self.SelectedFramesView, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 2, 1, 1, 1)
        self.bsave = QtWidgets.QPushButton(self.groupBox_2)
        self.bsave.setObjectName("bsave")
        self.gridLayout_3.addWidget(self.bsave, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 2, 0, 1, 4)
        self.groupBox = QtWidgets.QGroupBox(toVisionWidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, 9)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.startWithDVR = QtWidgets.QCheckBox(self.groupBox)
        self.startWithDVR.setChecked(False)
        self.startWithDVR.setObjectName("startWithDVR")
        self.gridLayout_2.addWidget(self.startWithDVR, 1, 0, 1, 1)
        self.stopFrameRecordSettings = QtWidgets.QStackedWidget(self.groupBox)
        self.stopFrameRecordSettings.setObjectName("stopFrameRecordSettings")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.nframes = QtWidgets.QSpinBox(self.page_3)
        self.nframes.setMaximumSize(QtCore.QSize(150, 16777215))
        self.nframes.setFrame(True)
        self.nframes.setMinimum(1)
        self.nframes.setMaximum(100000)
        self.nframes.setProperty("value", 100)
        self.nframes.setObjectName("nframes")
        self.verticalLayout_3.addWidget(self.nframes)
        self.stopFrameRecordSettings.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stopRecordFrames = QtWidgets.QPushButton(self.page_4)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/media-playback-stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopRecordFrames.setIcon(icon)
        self.stopRecordFrames.setObjectName("stopRecordFrames")
        self.verticalLayout_5.addWidget(self.stopRecordFrames)
        self.stopFrameRecordSettings.addWidget(self.page_4)
        self.gridLayout_2.addWidget(self.stopFrameRecordSettings, 3, 1, 1, 1)
        self.continuous = QtWidgets.QCheckBox(self.groupBox)
        self.continuous.setEnabled(False)
        self.continuous.setChecked(True)
        self.continuous.setObjectName("continuous")
        self.gridLayout_2.addWidget(self.continuous, 2, 1, 1, 1)
        self.startFrameRecordSettings = QtWidgets.QStackedWidget(self.groupBox)
        self.startFrameRecordSettings.setObjectName("startFrameRecordSettings")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.recordFrames = QtWidgets.QPushButton(self.page)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/media-record.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.recordFrames.setIcon(icon1)
        self.recordFrames.setObjectName("recordFrames")
        self.verticalLayout_4.addWidget(self.recordFrames)
        self.startFrameRecordSettings.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.delay = QtWidgets.QSpinBox(self.page_2)
        self.delay.setObjectName("delay")
        self.verticalLayout_2.addWidget(self.delay)
        self.startFrameRecordSettings.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.startFrameRecordSettings, 3, 0, 1, 1)
        self.stopWithDVR = QtWidgets.QCheckBox(self.groupBox)
        self.stopWithDVR.setObjectName("stopWithDVR")
        self.gridLayout_2.addWidget(self.stopWithDVR, 2, 0, 1, 1)
        self.skip = QtWidgets.QSpinBox(self.groupBox)
        self.skip.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.skip.setMinimum(1)
        self.skip.setMaximum(99)
        self.skip.setProperty("value", 5)
        self.skip.setObjectName("skip")
        self.gridLayout_2.addWidget(self.skip, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 4)

        self.retranslateUi(toVisionWidget)
        self.stopFrameRecordSettings.setCurrentIndex(1)
        self.startFrameRecordSettings.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(toVisionWidget)

    def retranslateUi(self, toVisionWidget):
        _translate = QtCore.QCoreApplication.translate
        toVisionWidget.setWindowTitle(_translate("toVisionWidget", "Form"))
        self.groupBox_2.setTitle(_translate("toVisionWidget", "Frame Selection"))
        self.pushButton_2.setText(_translate("toVisionWidget", "Clear Selected"))
        self.pushButton_3.setText(_translate("toVisionWidget", "Clear All"))
        self.bsave.setText(_translate("toVisionWidget", "Save Selected"))
        self.pushButton.setText(_translate("toVisionWidget", "Save All"))
        self.groupBox.setTitle(_translate("toVisionWidget", "Frame Capture"))
        self.startWithDVR.setText(_translate("toVisionWidget", "Start with DVR"))
        self.nframes.setSpecialValueText(_translate("toVisionWidget", "1 frame"))
        self.nframes.setSuffix(_translate("toVisionWidget", " frames"))
        self.nframes.setPrefix(_translate("toVisionWidget", "record "))
        self.stopRecordFrames.setStatusTip(_translate("toVisionWidget", "Stop recording"))
        self.stopRecordFrames.setText(_translate("toVisionWidget", "&Pause"))
        self.stopRecordFrames.setShortcut(_translate("toVisionWidget", "S"))
        self.continuous.setText(_translate("toVisionWidget", "Continuous Capture"))
        self.recordFrames.setStatusTip(_translate("toVisionWidget", "Record video"))
        self.recordFrames.setText(_translate("toVisionWidget", "&Record"))
        self.recordFrames.setShortcut(_translate("toVisionWidget", "R"))
        self.delay.setSuffix(_translate("toVisionWidget", " frames"))
        self.delay.setPrefix(_translate("toVisionWidget", "delay "))
        self.stopWithDVR.setText(_translate("toVisionWidget", "Stop with DVR"))
        self.skip.setSpecialValueText(_translate("toVisionWidget", "every frame"))
        self.skip.setSuffix(_translate("toVisionWidget", " video frames"))
        self.skip.setPrefix(_translate("toVisionWidget", "every "))
        self.label.setText(_translate("toVisionWidget", "Capture Vision Frame"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    toVisionWidget = QtWidgets.QWidget()
    ui = Ui_toVisionWidget()
    ui.setupUi(toVisionWidget)
    toVisionWidget.show()
    sys.exit(app.exec_())

