# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QVisionWidget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QVisionWidget(object):
    def setupUi(self, QVisionWidget):
        QVisionWidget.setObjectName("QVisionWidget")
        QVisionWidget.setEnabled(True)
        QVisionWidget.resize(600, 742)
        self.verticalLayout = QtWidgets.QVBoxLayout(QVisionWidget)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupProcess = QtWidgets.QGroupBox(QVisionWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupProcess.setFont(font)
        self.groupProcess.setObjectName("groupProcess")
        self.gridLayout = QtWidgets.QGridLayout(self.groupProcess)
        self.gridLayout.setContentsMargins(6, 2, 2, 2)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupProcess)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.skipBox = QtWidgets.QSpinBox(self.groupProcess)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skipBox.sizePolicy().hasHeightForWidth())
        self.skipBox.setSizePolicy(sizePolicy)
        self.skipBox.setWhatsThis("")
        self.skipBox.setPrefix("")
        self.skipBox.setMaximum(1000)
        self.skipBox.setProperty("value", 5)
        self.skipBox.setObjectName("skipBox")
        self.gridLayout.addWidget(self.skipBox, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupProcess)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.spinTol = QtWidgets.QDoubleSpinBox(self.groupProcess)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinTol.sizePolicy().hasHeightForWidth())
        self.spinTol.setSizePolicy(sizePolicy)
        self.spinTol.setPrefix("")
        self.spinTol.setDecimals(1)
        self.spinTol.setProperty("value", 5.0)
        self.spinTol.setObjectName("spinTol")
        self.gridLayout.addWidget(self.spinTol, 3, 1, 1, 1)
        self.breal = QtWidgets.QRadioButton(self.groupProcess)
        self.breal.setToolTip("")
        self.breal.setWhatsThis("")
        self.breal.setObjectName("breal")
        self.gridLayout.addWidget(self.breal, 1, 0, 1, 1)
        self.bpost = QtWidgets.QRadioButton(self.groupProcess)
        self.bpost.setToolTip("")
        self.bpost.setWhatsThis("")
        self.bpost.setChecked(True)
        self.bpost.setObjectName("bpost")
        self.gridLayout.addWidget(self.bpost, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupProcess)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.threshBox = QtWidgets.QDoubleSpinBox(self.groupProcess)
        self.threshBox.setDecimals(1)
        self.threshBox.setMinimum(20.0)
        self.threshBox.setMaximum(100.0)
        self.threshBox.setProperty("value", 50.0)
        self.threshBox.setObjectName("threshBox")
        self.gridLayout.addWidget(self.threshBox, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupProcess)
        self.groupPipeline = QtWidgets.QGroupBox(QVisionWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupPipeline.sizePolicy().hasHeightForWidth())
        self.groupPipeline.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupPipeline.setFont(font)
        self.groupPipeline.setObjectName("groupPipeline")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupPipeline)
        self.horizontalLayout.setContentsMargins(6, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bDetect = QtWidgets.QCheckBox(self.groupPipeline)
        self.bDetect.setObjectName("bDetect")
        self.horizontalLayout.addWidget(self.bDetect)
        self.bEstimate = QtWidgets.QCheckBox(self.groupPipeline)
        self.bEstimate.setObjectName("bEstimate")
        self.horizontalLayout.addWidget(self.bEstimate)
        self.bRefine = QtWidgets.QCheckBox(self.groupPipeline)
        self.bRefine.setObjectName("bRefine")
        self.horizontalLayout.addWidget(self.bRefine)
        self.verticalLayout.addWidget(self.groupPipeline)
        self.groupExport = QtWidgets.QGroupBox(QVisionWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupExport.sizePolicy().hasHeightForWidth())
        self.groupExport.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupExport.setFont(font)
        self.groupExport.setObjectName("groupExport")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupExport)
        self.formLayout_2.setContentsMargins(6, 2, 2, 2)
        self.formLayout_2.setHorizontalSpacing(12)
        self.formLayout_2.setVerticalSpacing(2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.checkFrames = QtWidgets.QCheckBox(self.groupExport)
        self.checkFrames.setChecked(False)
        self.checkFrames.setTristate(False)
        self.checkFrames.setObjectName("checkFrames")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.checkFrames)
        self.checkTrajectories = QtWidgets.QCheckBox(self.groupExport)
        self.checkTrajectories.setObjectName("checkTrajectories")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.checkTrajectories)
        self.checkFeatureData = QtWidgets.QCheckBox(self.groupExport)
        self.checkFeatureData.setObjectName("checkFeatureData")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.checkFeatureData)
        self.verticalLayout.addWidget(self.groupExport)
        self.plot2 = PlotWidget(QVisionWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.plot2.sizePolicy().hasHeightForWidth())
        self.plot2.setSizePolicy(sizePolicy)
        self.plot2.setObjectName("plot2")
        self.verticalLayout.addWidget(self.plot2)
        self.plot1 = PlotWidget(QVisionWidget)
        self.plot1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.plot1.sizePolicy().hasHeightForWidth())
        self.plot1.setSizePolicy(sizePolicy)
        self.plot1.setStatusTip("")
        self.plot1.setObjectName("plot1")
        self.verticalLayout.addWidget(self.plot1)

        self.retranslateUi(QVisionWidget)
        QtCore.QMetaObject.connectSlotsByName(QVisionWidget)

    def retranslateUi(self, QVisionWidget):
        _translate = QtCore.QCoreApplication.translate
        QVisionWidget.setWindowTitle(_translate("QVisionWidget", "Form"))
        self.groupProcess.setTitle(_translate("QVisionWidget", "Processing"))
        self.label_2.setStatusTip(_translate("QVisionWidget", "Skip intermediate frames to reduce latency"))
        self.label_2.setText(_translate("QVisionWidget", "Skip "))
        self.skipBox.setStatusTip(_translate("QVisionWidget", "Skip intermediate frames to reduce latency"))
        self.skipBox.setSuffix(_translate("QVisionWidget", " frames"))
        self.label.setStatusTip(_translate("QVisionWidget", "Maximum distance features can move between frames in order to be linked to the same Trajectory"))
        self.label.setText(_translate("QVisionWidget", "Search range"))
        self.spinTol.setStatusTip(_translate("QVisionWidget", "Maximum distance features can move between frames in order to be linked to the same Trajectory."))
        self.spinTol.setSuffix(_translate("QVisionWidget", " pixels"))
        self.breal.setStatusTip(_translate("QVisionWidget", "Process data in real-time"))
        self.breal.setText(_translate("QVisionWidget", "Real-time"))
        self.bpost.setStatusTip(_translate("QVisionWidget", "Process data after recording video"))
        self.bpost.setText(_translate("QVisionWidget", "Post-process"))
        self.label_3.setStatusTip(_translate("QVisionWidget", "Confidence threshold for detections. Throw away features detected below this confidence."))
        self.label_3.setText(_translate("QVisionWidget", "Confidence"))
        self.threshBox.setStatusTip(_translate("QVisionWidget", "Confidence threshold for detections. Throw away features detected below this confidence."))
        self.threshBox.setSuffix(_translate("QVisionWidget", " %"))
        self.groupPipeline.setTitle(_translate("QVisionWidget", "Analysis pipeline"))
        self.bDetect.setStatusTip(_translate("QVisionWidget", "Deep neural network (x, y) feature detection"))
        self.bDetect.setText(_translate("QVisionWidget", "Detect"))
        self.bEstimate.setStatusTip(_translate("QVisionWidget", "Deep neural network (x, y, z) feature detection and holographic characterization"))
        self.bEstimate.setText(_translate("QVisionWidget", "Estimate"))
        self.bRefine.setStatusTip(_translate("QVisionWidget", "Deep neural network pipeline with precision holographic characterization"))
        self.bRefine.setText(_translate("QVisionWidget", "Refine"))
        self.groupExport.setStatusTip(_translate("QVisionWidget", "See https://github.com/davidgrier/pylorenzmie for Video, Frame, Trajectory, and Feature documentation"))
        self.groupExport.setTitle(_translate("QVisionWidget", "Save"))
        self.checkFrames.setStatusTip(_translate("QVisionWidget", "Export Frames from video recordings"))
        self.checkFrames.setText(_translate("QVisionWidget", "Frames"))
        self.checkTrajectories.setStatusTip(_translate("QVisionWidget", "Export Trajectories from video recordings"))
        self.checkTrajectories.setText(_translate("QVisionWidget", "Trajectories"))
        self.checkFeatureData.setStatusTip(_translate("QVisionWidget", "Save cropped Feature data when exporting Frames and/or Trajectories"))
        self.checkFeatureData.setText(_translate("QVisionWidget", "Feature data"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QVisionWidget = QtWidgets.QWidget()
    ui = Ui_QVisionWidget()
    ui.setupUi(QVisionWidget)
    QVisionWidget.show()
    sys.exit(app.exec_())

